// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {database} from '../models';
import {store} from '../models';

export function ConfigureAPIKey(arg1:string):Promise<void>;

export function GetAPIKey():Promise<string>;

export function GetAvailableSounds():Promise<Array<string>>;

export function GetFilterByUser():Promise<boolean>;

export function GetNotificationConfig():Promise<main.NotificationConfig>;

export function GetOpenIncidents(arg1:Array<string>):Promise<Array<database.IncidentData>>;

export function GetRateLimitStatus():Promise<Record<string, any>>;

export function GetResolvedIncidents(arg1:Array<string>):Promise<Array<database.IncidentData>>;

export function GetSelectedServices():Promise<Array<string>>;

export function GetServicesConfig():Promise<store.ServicesConfig>;

export function IsNotificationSnoozed():Promise<boolean>;

export function ReadFile(arg1:string):Promise<string>;

export function RemoveServicesConfig():Promise<void>;

export function SetFilterByUser(arg1:boolean):Promise<void>;

export function SetNotificationEnabled(arg1:boolean):Promise<void>;

export function SetNotificationSound(arg1:string):Promise<void>;

export function SetSelectedServices(arg1:Array<string>):Promise<void>;

export function SnoozeNotificationSound(arg1:number):Promise<void>;

export function StartPolling():Promise<void>;

export function StartResolvedPolling():Promise<void>;

export function StopPolling():Promise<void>;

export function StopResolvedPolling():Promise<void>;

export function TestNotificationSound():Promise<void>;

export function UnsnoozeNotificationSound():Promise<void>;

export function UploadServicesConfig(arg1:string):Promise<void>;
