// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgeIncident(arg1) {
  return window['go']['main']['App']['AcknowledgeIncident'](arg1);
}

export function AddIncidentNote(arg1, arg2) {
  return window['go']['main']['App']['AddIncidentNote'](arg1, arg2);
}

export function DeleteService(arg1) {
  return window['go']['main']['App']['DeleteService'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function EscalateIncident(arg1, arg2) {
  return window['go']['main']['App']['EscalateIncident'](arg1, arg2);
}

export function FetchAvailableServices() {
  return window['go']['main']['App']['FetchAvailableServices']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDraftNote(arg1) {
  return window['go']['main']['App']['GetDraftNote'](arg1);
}

export function GetIncidentAlerts(arg1) {
  return window['go']['main']['App']['GetIncidentAlerts'](arg1);
}

export function GetIncidents(arg1) {
  return window['go']['main']['App']['GetIncidents'](arg1);
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function MergeIncidents(arg1, arg2) {
  return window['go']['main']['App']['MergeIncidents'](arg1, arg2);
}

export function OpenIncidentInBrowser(arg1) {
  return window['go']['main']['App']['OpenIncidentInBrowser'](arg1);
}

export function PinIncident(arg1, arg2) {
  return window['go']['main']['App']['PinIncident'](arg1, arg2);
}

export function ResolveIncident(arg1) {
  return window['go']['main']['App']['ResolveIncident'](arg1);
}

export function SaveDraftNote(arg1) {
  return window['go']['main']['App']['SaveDraftNote'](arg1);
}

export function SaveService(arg1) {
  return window['go']['main']['App']['SaveService'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}

export function SelectSoundFolder() {
  return window['go']['main']['App']['SelectSoundFolder']();
}

export function SnoozeIncident(arg1, arg2) {
  return window['go']['main']['App']['SnoozeIncident'](arg1, arg2);
}

export function ToggleService(arg1, arg2) {
  return window['go']['main']['App']['ToggleService'](arg1, arg2);
}
