// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {database} from '../models';
import {main} from '../models';

export function AcknowledgeIncident(arg1:string):Promise<void>;

export function AddIncidentNote(arg1:string,arg2:string):Promise<void>;

export function DeleteService(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:number):Promise<void>;

export function EscalateIncident(arg1:string,arg2:string):Promise<void>;

export function FetchAvailableServices():Promise<Array<services.Service>>;

export function GetCurrentUser():Promise<database.User>;

export function GetDraftNote(arg1:string):Promise<database.DraftNote>;

export function GetIncidentAlerts(arg1:string):Promise<Array<services.Alert>>;

export function GetIncidents(arg1:Array<string>):Promise<Array<database.CachedIncident>>;

export function GetServices():Promise<Array<database.Service>>;

export function GetSettings():Promise<main.AppSettings>;

export function GetTemplates():Promise<Array<database.Template>>;

export function MergeIncidents(arg1:Array<string>,arg2:string):Promise<void>;

export function OpenIncidentInBrowser(arg1:string):Promise<void>;

export function PinIncident(arg1:string,arg2:boolean):Promise<void>;

export function ResolveIncident(arg1:string):Promise<void>;

export function SaveDraftNote(arg1:database.DraftNote):Promise<void>;

export function SaveService(arg1:database.Service):Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SaveTemplate(arg1:database.Template):Promise<void>;

export function SelectSoundFolder():Promise<string>;

export function SnoozeIncident(arg1:string,arg2:number):Promise<void>;

export function ToggleService(arg1:string,arg2:boolean):Promise<void>;
