// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureAPIKey(arg1) {
  return window['go']['main']['App']['ConfigureAPIKey'](arg1);
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetFilterByUser() {
  return window['go']['main']['App']['GetFilterByUser']();
}

export function GetOpenIncidents(arg1) {
  return window['go']['main']['App']['GetOpenIncidents'](arg1);
}

export function GetResolvedIncidents(arg1) {
  return window['go']['main']['App']['GetResolvedIncidents'](arg1);
}

export function GetSelectedServices() {
  return window['go']['main']['App']['GetSelectedServices']();
}

export function GetServicesConfig() {
  return window['go']['main']['App']['GetServicesConfig']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RemoveServicesConfig() {
  return window['go']['main']['App']['RemoveServicesConfig']();
}

export function SetFilterByUser(arg1) {
  return window['go']['main']['App']['SetFilterByUser'](arg1);
}

export function SetSelectedServices(arg1) {
  return window['go']['main']['App']['SetSelectedServices'](arg1);
}

export function StartPolling() {
  return window['go']['main']['App']['StartPolling']();
}

export function StopPolling() {
  return window['go']['main']['App']['StopPolling']();
}

export function UploadServicesConfig(arg1) {
  return window['go']['main']['App']['UploadServicesConfig'](arg1);
}
