// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureAPIKey(arg1) {
  return window['go']['main']['App']['ConfigureAPIKey'](arg1);
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetAvailableSounds() {
  return window['go']['main']['App']['GetAvailableSounds']();
}

export function GetBrowserRedirect() {
  return window['go']['main']['App']['GetBrowserRedirect']();
}

export function GetFilterByUser() {
  return window['go']['main']['App']['GetFilterByUser']();
}

export function GetIncidentSidebarData(arg1) {
  return window['go']['main']['App']['GetIncidentSidebarData'](arg1);
}

export function GetNotificationConfig() {
  return window['go']['main']['App']['GetNotificationConfig']();
}

export function GetOpenIncidents(arg1) {
  return window['go']['main']['App']['GetOpenIncidents'](arg1);
}

export function GetRateLimitStatus() {
  return window['go']['main']['App']['GetRateLimitStatus']();
}

export function GetResolvedIncidents(arg1) {
  return window['go']['main']['App']['GetResolvedIncidents'](arg1);
}

export function GetSelectedServices() {
  return window['go']['main']['App']['GetSelectedServices']();
}

export function GetServiceNameByID(arg1) {
  return window['go']['main']['App']['GetServiceNameByID'](arg1);
}

export function GetServicesConfig() {
  return window['go']['main']['App']['GetServicesConfig']();
}

export function IsNotificationSnoozed() {
  return window['go']['main']['App']['IsNotificationSnoozed']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RemoveServicesConfig() {
  return window['go']['main']['App']['RemoveServicesConfig']();
}

export function SetBrowserRedirect(arg1) {
  return window['go']['main']['App']['SetBrowserRedirect'](arg1);
}

export function SetFilterByUser(arg1) {
  return window['go']['main']['App']['SetFilterByUser'](arg1);
}

export function SetNotificationEnabled(arg1) {
  return window['go']['main']['App']['SetNotificationEnabled'](arg1);
}

export function SetNotificationSound(arg1) {
  return window['go']['main']['App']['SetNotificationSound'](arg1);
}

export function SetSelectedServices(arg1) {
  return window['go']['main']['App']['SetSelectedServices'](arg1);
}

export function SnoozeNotificationSound(arg1) {
  return window['go']['main']['App']['SnoozeNotificationSound'](arg1);
}

export function StartPolling() {
  return window['go']['main']['App']['StartPolling']();
}

export function StartResolvedPolling() {
  return window['go']['main']['App']['StartResolvedPolling']();
}

export function StartUserPolling() {
  return window['go']['main']['App']['StartUserPolling']();
}

export function StopPolling() {
  return window['go']['main']['App']['StopPolling']();
}

export function StopResolvedPolling() {
  return window['go']['main']['App']['StopResolvedPolling']();
}

export function StopUserPolling() {
  return window['go']['main']['App']['StopUserPolling']();
}

export function TestNotificationSound() {
  return window['go']['main']['App']['TestNotificationSound']();
}

export function ToggleServiceDisabled(arg1) {
  return window['go']['main']['App']['ToggleServiceDisabled'](arg1);
}

export function UnsnoozeNotificationSound() {
  return window['go']['main']['App']['UnsnoozeNotificationSound']();
}

export function UploadServicesConfig(arg1) {
  return window['go']['main']['App']['UploadServicesConfig'](arg1);
}
