// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {store} from '../models';

export function ConfigureAPIKey(arg1:string):Promise<void>;

export function GetAPIKey():Promise<string>;

export function GetOpenIncidents():Promise<Array<database.IncidentData>>;

export function GetResolvedIncidents():Promise<Array<database.IncidentData>>;

export function GetServicesConfig():Promise<store.ServicesConfig>;

export function ReadFile(arg1:string):Promise<string>;

export function SetSelectedServices(arg1:Array<string>):Promise<void>;

export function StartPolling():Promise<void>;

export function StopPolling():Promise<void>;

export function UploadServicesConfig(arg1:string):Promise<void>;
